FROM golang:alpine AS builder
RUN apk update && apk add --no-cache git
WORKDIR $GOPATH/src/taskshare.com/app/
COPY ./app .
RUN go mod init && go get -d -v \
    && go build -o /ola

FROM scratch
COPY --from=builder /ola /go/bin/ola
ENTRYPOINT ["/go/bin/ola"]